### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by AShabana** [awsdocs/amazon-ecs-developer-guide#1]
When try to run it as below `ecs-cli compose --file docker-compose.yml up --create-log-groups --ecs-profile ec2-ecs-tutorial --aws-profile pprofile`

it fails with below logs

```
WARN[0000] Skipping unsupported YAML option for service...  option name="network_mode" service name=restcomm
WARN[0000] Skipping unsupported YAML option for service...  option name=restart service name=restcomm
INFO[0001] Using ECS task definition                     TaskDefinition="root:10"
WARN[0001] Failed to create log group tutorial-rc in us-west-2: The specified log group already exists
ERRO[0001] Error running tasks                           error="InvalidParameterException: No Container Instances were found in your cluster.\n\tstatus code: 400, request id: 1bc1cad8-05b3-11e8-93c3-3f478d00f51d" task definition="arn:aws:ecs:us-west-2:966021346097:task-definition/root:10"
FATA[0001] InvalidParameterException: No Container Instances were found in your cluster.
	status code: 400, request id: 1bc1cad8-05b3-11e8-93c3-3f478d00f51d
```

**Comment by joelbrandenburg** [comment]
Seems you're having several issues going on here.

1) What version of the ECS CLI are you using?  Run "ecs-cli --version" and let me know.  

2) You only need the "--create-log-groups" flag if the log groups aren't already created so you can leave that off since it appears they already exist.

3) If you're using the EC2 launch type and don't have any container instances in your cluster then it will fail.  If you're attempting to use the Fargate launch type then you need to specify "--launch-type FARGATE" in your command.

**Comment by lowercase00** [comment]
Same problem here while trying to ECS tutorial.
Using `ecs-cli version 1.21.0 (bb0b8f0)`
Trying to understand how to effectively create the cluster (including its instances) with the `ecs-cli`.
Also using EC2 launch type, but didn't understand your third point:
> If you're using the EC2 launch type and don't have any container instances in your cluster then it will fail.
Does that mean that I have to create the EC2 instances separately?

**Comment by nilleb** [comment]
@lowercase00 the problem seems to be related to the instance-type t4g.micro - if I do not specify the type, then I get my instances
