### ISSUE TITLE
ENI trunking document is lack of unsupported instance type of T2/T3

### ISSUE THREAD

**Issue by SypherSu** [awsdocs/amazon-ecs-developer-guide#125]
Base on the AWS container road map's member mentioned, currently **T2** and **T3** instance type is not supported due to technical constraints .

https://github.com/aws/containers-roadmap/issues/7#issuecomment-545056980

As currently document, it seems will misleading customer. Because customer only see the notice "The c5n, m5n, m5dn, r5n, and r5dn instance types are not supported.". 

I expected that we can add the **t2** and **t3** on this unsupported notice in order to make customer more clarify.

**Comment by joelbrandenburg** [comment]
The reason we specifically call out the c5n, m5n, m5dn, r5n, and r5dn instance types is because we support other instances in those same families, but not those.  If we also mention t2 and t3, some would wonder why we don't list out all the other instance types we don't mention.

I can update the note in the documentation to make it clear why we call out those instance types specifically.
