### ISSUE TITLE
Target Tracking Scaling Policies --Add data points for scale-in actions

### ISSUE THREAD

**Issue by nameprabhat** [awsdocs/amazon-ecs-developer-guide#150]
Hello team,

In [this page of documention](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/service-autoscaling-targettracking.html#targettracking-considerations) currently customer have visibility for target metric value and actual metric data points in cloudwatch ..but they don't have any clear data point which states when would scale-in occur.

ECS tasks scale in process is vaguely mentioned in [considerations](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/service-autoscaling-targettracking.html#targettracking-considerations) link... can we please add a new example scale in action...which clearly mentions the scopes of target metric value setup my customer, actual metric data points in cloudwatch and data points when customer should expect the scale in action to occur.

**Comment by Reneehi** [comment]
Hi, I write for the Application Auto Scaling docs. ECS service scaling is integrated with Application Auto Scaling. I noticed this issue was raised a while ago. Sorry if this is coming very late! 

We have a section that talks about the behavior of target tracking for scale out and scale in [here](https://docs.aws.amazon.com/autoscaling/application/userguide/what-is-application-auto-scaling.html). If you want to see exactly how this looks per target tracking scaling policy, you're welcome to look at the alarms in CloudWatch after you create a target tracking scaling policy. Just a word of warning that you can't make changes to the alarm or specify a different alarm configuration for target tracking. The alarms for target tracking are managed by AWS. 

On a related note, if you want your target tracking scaling policy to scale in when a metric's value is 0, that means you need a metric that will emit zeros. Currently, I believe an Application Load Balancer (request count per target) or SQS queue metric will emit zeros when there is no traffic. You can also use step scaling in combination with target tracking for more advanced use cases, like scaling up from 0 as soon as one new request or message arrives.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
